backend:
  name: git-gateway
  branch: master
  repo: DarkMatterOregon/dark-matter-static-web

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
      - { label: 'Headshot', name: 'headshot', widget: 'image' }
      - { label: 'LinkedIn ID', name: 'linkedinid', widget: 'string' }
      - { label: 'GetHub ID', name: 'githubid', widget: 'string' }
  
  - name: 'pages'
    label: 'Pages'
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
